SUPPORTED_LANGUAGES = [
    {"code": "zh-Hans", "name": "Chinese Simplified", "nativeName": "中文简体"},
    {"code": "ja", "name": "Japanese", "nativeName": "日本語"},
    {"code": "af", "name": "Afrikaans", "nativeName": "Afrikaans"},
    {"code": "ar", "name": "Arabic", "nativeName": "العربية"},
    {"code": "bg", "name": "Bulgarian", "nativeName": "Български"},
    {"code": "bn", "name": "Bangla", "nativeName": "বাংলা"},
    {"code": "bs", "name": "Bosnian", "nativeName": "Bosnian"},
    {"code": "ca", "name": "Catalan", "nativeName": "Català"},
    {"code": "cs", "name": "Czech", "nativeName": "Čeština"},
    {"code": "cy", "name": "Welsh", "nativeName": "Cymraeg"},
    {"code": "da", "name": "Danish", "nativeName": "Dansk"},
    {"code": "de", "name": "German", "nativeName": "Deutsch"},
    {"code": "el", "name": "Greek", "nativeName": "Ελληνικά"},
    # {"code": "en", "name": "English", "nativeName": "English"},
    {"code": "es", "name": "Spanish", "nativeName": "Español"},
    {"code": "et", "name": "Estonian", "nativeName": "Eesti"},
    {"code": "fa", "name": "Persian", "nativeName": "فارسی"},
    {"code": "fi", "name": "Finnish", "nativeName": "Suomi"},
    {"code": "fr", "name": "French", "nativeName": "Français"},
    {"code": "he", "name": "Hebrew", "nativeName": "עברית"},
    {"code": "hi", "name": "Hindi", "nativeName": "हिन्दी"},
    {"code": "hr", "name": "Croatian", "nativeName": "Hrvatski"},
    {"code": "hu", "name": "Hungarian", "nativeName": "Magyar"},
    {"code": "id", "name": "Indonesian", "nativeName": "Indonesia"},
    {"code": "is", "name": "Icelandic", "nativeName": "Íslenska"},
    {"code": "it", "name": "Italian", "nativeName": "Italiano"},
    {"code": "ko", "name": "Korean", "nativeName": "한국어"},
    {"code": "lt", "name": "Lithuanian", "nativeName": "Lietuvių"},
    {"code": "lv", "name": "Latvian", "nativeName": "Latviešu"},
    {"code": "ms", "name": "Malay", "nativeName": "Melayu"},
    {"code": "mt", "name": "Maltese", "nativeName": "Malti"},
    {"code": "mww", "name": "Hmong Daw", "nativeName": "Hmong Daw"},
    {"code": "nb", "name": "Norwegian", "nativeName": "Norsk Bokmål"},
    {"code": "nl", "name": "Dutch", "nativeName": "Nederlands"},
    {"code": "pl", "name": "Polish", "nativeName": "Polski"},
    {"code": "pt", "name": "Portuguese", "nativeName": "Português"},
    {"code": "ro", "name": "Romanian", "nativeName": "Română"},
    {"code": "ru", "name": "Russian", "nativeName": "Русский"},
    {"code": "sk", "name": "Slovak", "nativeName": "Slovenčina"},
    {"code": "sl", "name": "Slovenian", "nativeName": "Slovenščina"},
    {"code": "sr-Latn", "name": "Serbian", "nativeName": "Srpski"},
    {"code": "sv", "name": "Swedish", "nativeName": "Svenska"},
    {"code": "sw", "name": "Swahili", "nativeName": "Kiswahili"},
    {"code": "ta", "name": "Tamil", "nativeName": "தமிழ்"},
    {"code": "th", "name": "Thai", "nativeName": "ไทย"},
    {"code": "tlh-Latn", "name": "Klingon", "nativeName": "Klingon"},
    {"code": "tr", "name": "Turkish", "nativeName": "Türkçe"},
    {"code": "uk", "name": "Ukrainian", "nativeName": "Українська"},
    {"code": "ur", "name": "Urdu", "nativeName": "اردو"},
    {"code": "vi", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
]

LANGUAGES_CODES = {lang["code"] for lang in SUPPORTED_LANGUAGES}
